layout_spectrum: 0.61119063252869
typography_spectrum: 0.17467805218384924
color:
  brandStrength: 0.44078903362477695
  lightness: 0.8927835599243604
  saturation: 0.8180796247025455
  rhythmicContrast: 0.787838143049601
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5117710a-971c-43a5-a48b-55637795740c.png
name: Generation Blue
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/baaf4a9a-eb90-418d-b37b-b3e953b30e64.png
title: We believe in the future
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FjmQCpW1kJTA%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DjmQCpW1kJTA&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FjmQCpW1kJTA%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Alfredo Barroso
          url: 'https://www.youtube.com/user/azuloceano'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: www.youtube.com
      keywords:
        - spadefish
        - spade fish
        - fish
        - school
        - underwater
        - sea
        - ocean
        - wildlife
        - diving
        - biodiversity
        - underthesea
        - underwaterphotography
        - alfredobarroso
        - azuloceano
      description: Uploaded by Alfredo Barroso on 2015-05-06.
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=jmQCpW1kJTA&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=jmQCpW1kJTA&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=jmQCpW1kJTA&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=jmQCpW1kJTA&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=jmQCpW1kJTA&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=jmQCpW1kJTA'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=jmQCpW1kJTA
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=jmQCpW1kJTA
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://www.youtube.com/watch?v=jmQCpW1kJTA'
      title: SPADEFISH 2
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Protect what you love. Have fun. Invest in Life.
purpose:
  - type: external
    label: Subscribe for updates
    url: 'http://lists.generation.blue/'
url: 'https://generation.blue/'
analytics:
  google: UA-113071973-1
github: true
author:
  name: >-
    GenBlue<br/>10 Anson Road<br/>#27-15 International Plaza<br/>Singapore
    079903
